name: build-packages

on:
  pull_request:
    types: [closed]

jobs:
  BuildPackages:
    if: github.event.pull_request.merged
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
      os: [macos-latest, windows-latest, ubuntu-18.04]
      include:
        - os: windows-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1
    - name: Inspect Payload
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}      
      run: |
        cat ${GITHUB_EVENT_PATH}
        # TODO need to get the submodule updated name from the branch merged
        sender=$(jq --raw-output .sender.login "${GITHUB_EVENT_PATH}")
        echo "Sender is $sender"
        label=$(jq --raw-output .pull_request.base.label "${GITHUB_EVENT_PATH}")
        echo "Repository and branch to open pull request against is $label"
        label_from=$(jq --raw-output .pull_request.head.label "${GITHUB_EVENT_PATH}")
        echo "Repository and branch creating pull request: $label_from"
